### ISSUE TITLE
@import sass Hot update

### ISSUE THREAD

**Issue by Topthinking** [giuseppeg/styled-jsx-plugin-sass#13]
```scss
<style jsx>{`
@import "styles/mixin.scss";
a {
   color:$selected;
 }
 `}</style>
```
When I change the sass file. `styles/mixin.scss`

The thermal update does not take effect.
