### ISSUE TITLE
Space added after variable

### ISSUE THREAD

**Issue by chuntley** [giuseppeg/styled-jsx-plugin-sass#7]
The following code:

```
const height = 100;

<style jsx>{`
   .test { height: ${height}px; }
`}</style>
```

Produces this CSS:

```
.test { height: 100 px; }
```

The expected result should be the following valid CSS:

```
.test { height: 100px; }
```

**Comment by giuseppeg** [comment]
Fixed by #6

**Comment by RobinCodeX** [comment]
I met the same problem with bulma.
https://github.com/jgthms/bulma/blob/bf0578090d8b050b5476bff38b970d05d238a3b5/sass/elements/tag.sass#L57-L63

Result:
```css
.tag:not(body) .is-white {
    background-color: white;
    color: #0a0a0a;
}

.tag:not(body) .is-black {
    background-color: #0a0a0a;
    color: white;
}

.tag:not(body) .is-light {
    background-color: whitesmoke;
    color: #363636;
}

.tag:not(body) .is-dark {
    background-color: #363636;
    color: whitesmoke;
}

.tag:not(body) .is-primary {
    background-color: #00d1b2;
    color: #fff;
}

.tag:not(body) .is-link {
    background-color: #3273dc;
    color: #fff;
}

...
```

Normal:
```css
.tag:not(body).is-white {
    background-color: white;
    color: #0a0a0a;
}

.tag:not(body).is-black {
    background-color: #0a0a0a;
    color: white;
}

.tag:not(body).is-light {
    background-color: whitesmoke;
    color: #363636;
}

.tag:not(body).is-dark {
    background-color: #363636;
    color: whitesmoke;
}

.tag:not(body).is-primary {
    background-color: #00d1b2;
    color: #fff;
}

.tag:not(body).is-link {
    background-color: #3273dc;
    color: #fff;
}

...
```
